/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriveRouteImport } from './routes/_drive'
import { Route as DriveIndexRouteImport } from './routes/_drive/index'
import { Route as DriveTrashRouteImport } from './routes/_drive/trash'
import { Route as DriveStarredRouteImport } from './routes/_drive/starred'
import { Route as DriveSharedRouteImport } from './routes/_drive/shared'
import { Route as DriveRecentRouteImport } from './routes/_drive/recent'

const DriveRoute = DriveRouteImport.update({
  id: '/_drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveRoute,
} as any)
const DriveTrashRoute = DriveTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DriveRoute,
} as any)
const DriveStarredRoute = DriveStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => DriveRoute,
} as any)
const DriveSharedRoute = DriveSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DriveRoute,
} as any)
const DriveRecentRoute = DriveRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => DriveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DriveIndexRoute
  '/recent': typeof DriveRecentRoute
  '/shared': typeof DriveSharedRoute
  '/starred': typeof DriveStarredRoute
  '/trash': typeof DriveTrashRoute
}
export interface FileRoutesByTo {
  '/recent': typeof DriveRecentRoute
  '/shared': typeof DriveSharedRoute
  '/starred': typeof DriveStarredRoute
  '/trash': typeof DriveTrashRoute
  '/': typeof DriveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_drive': typeof DriveRouteWithChildren
  '/_drive/recent': typeof DriveRecentRoute
  '/_drive/shared': typeof DriveSharedRoute
  '/_drive/starred': typeof DriveStarredRoute
  '/_drive/trash': typeof DriveTrashRoute
  '/_drive/': typeof DriveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recent' | '/shared' | '/starred' | '/trash'
  fileRoutesByTo: FileRoutesByTo
  to: '/recent' | '/shared' | '/starred' | '/trash' | '/'
  id:
    | '__root__'
    | '/_drive'
    | '/_drive/recent'
    | '/_drive/shared'
    | '/_drive/starred'
    | '/_drive/trash'
    | '/_drive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DriveRoute: typeof DriveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_drive': {
      id: '/_drive'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_drive/': {
      id: '/_drive/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/trash': {
      id: '/_drive/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof DriveTrashRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/starred': {
      id: '/_drive/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof DriveStarredRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/shared': {
      id: '/_drive/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof DriveSharedRouteImport
      parentRoute: typeof DriveRoute
    }
    '/_drive/recent': {
      id: '/_drive/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof DriveRecentRouteImport
      parentRoute: typeof DriveRoute
    }
  }
}

interface DriveRouteChildren {
  DriveRecentRoute: typeof DriveRecentRoute
  DriveSharedRoute: typeof DriveSharedRoute
  DriveStarredRoute: typeof DriveStarredRoute
  DriveTrashRoute: typeof DriveTrashRoute
  DriveIndexRoute: typeof DriveIndexRoute
}

const DriveRouteChildren: DriveRouteChildren = {
  DriveRecentRoute: DriveRecentRoute,
  DriveSharedRoute: DriveSharedRoute,
  DriveStarredRoute: DriveStarredRoute,
  DriveTrashRoute: DriveTrashRoute,
  DriveIndexRoute: DriveIndexRoute,
}

const DriveRouteWithChildren = DriveRoute._addFileChildren(DriveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DriveRoute: DriveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
